#Extract Library
```{r}
source("C:\\Research\\TP Analysis\\Library\\Library.R")
```
#Access Data
```{r}
Trend_all <- read.csv("C:\\Research\\TP Analysis\\Cache\\Temporal Change\\Reach_Level_Trend_Original_All.csv")
NHD_Shape <- st_read("C:\\Research\\TP Analysis\\Shape File\\NHDShapeFile\\nhdplusv2_modified_v1.0.shp")
Gauge_location <- read.csv("C:\\Research\\TP Analysis\\Cache\\Riverine TP database\\Gauge_Location_Save.csv")
```

#Analysis
```{r}
NHD_Shape <- left_join(NHD_Shape, Trend_all, by = c("ID"= "R_ID"))

NHD_Shape <- replace(NHD_Shape, is.na(NHD_Shape), 0)

Gauge_location <- Gauge_location%>%filter(MonitoringLocationIdentifier%in%NHD_Shape$G_ID)

Gauge_location <- Gauge_location%>%left_join(NHD_Shape, by= c("MonitoringLocationIdentifier" = "G_ID"))

Gauge_location <- Gauge_location%>%select(MonitoringLocationIdentifier, ID, lat, lon, Year, Correlation)

Gauge_location<- Gauge_location%>% 
  st_as_sf(coords = c(x="lon", y="lat"), crs=4326)

Gauge_location <- Gauge_location%>%filter(Year >= 15)

 # Define a color palette
          color_palette_1 <- colorRampPalette(c("yellow", "green"))
          
          # Generate a vector of colors
          color_scale_positive <- color_palette_1(100)
          
          
                      # Define a color palette
          color_palette_2 <- colorRampPalette(c("red", "yellow"))
        
          # Generate a vector of colors
          color_scale_negative <- color_palette_2(100)
      
```

#Plot the figure 
```{r}
# Set the CRS
crs <- st_crs(2163)

# Get the map data for the US
us <- ne_countries(scale = "medium", country = "United States of America", returnclass = "sf")

# Transform to the desired CRS
us_transformed <- st_transform(us, crs)

Gauge_location<- Gauge_location%>%filter(Year >= 3)

# Calculate breaks for skewed distribution
breaks <- c(15, 30)

# Define labels for breaks
labels <- c("15", "30")

trend_validation <- ggplot() + 
  geom_sf(data = us_transformed, fill = "grey0", color = "grey0", size = 1) +
  geom_sf(data = NHD_Shape, color = "grey30", lwd = NHD_Shape$StrmOrd / 5) +
  geom_sf(data = Gauge_location %>% filter(Year >= 15), 
          aes(color = Correlation), size = Gauge_location$Year/2.5, alpha = 0.5) +  # Size is now in aes()
  scale_color_gradientn(colors = c(color_scale_negative, color_scale_positive), limits = c(-1, 1)) +
  scale_size_continuous(breaks = breaks, labels = labels) +  # Adjust size scale
  coord_sf(crs = st_crs(2163), xlim = c(-2500000, 2500000), ylim = c(-2300000, 730000)) +
  theme(panel.grid = element_blank(),
        plot.title = element_text(size = 20),  
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.title.x = element_blank(),  # Remove x-axis label
        axis.title.y = element_blank(),  # Remove y-axis label
        axis.text.x = element_blank(),   # Remove x-axis tick labels
        axis.text.y = element_blank(),   # Remove y-axis tick labels
        axis.ticks = element_blank(),    # Remove ticks from both axes
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 15),  # Adjust legend label size
        legend.key.size = unit(2.5, "lines")) + 
  labs(title = "a)", color = "Correlation Value")


# Create the histogram as a ggplot object
hist_TP <- ggplot(Gauge_location %>% filter(Year >= 3), aes(x = Correlation)) +
  geom_histogram(color = "black", fill = "lightblue", size = 1, bins = 10) +  # Change size for line thickness
  labs(x = "Correlation", y = "Frequency") +  # Change x and y axis names
  theme(
    axis.text = element_text(size = 12),  # Adjust font size for axis text
    axis.title = element_text(size = 15),  # Adjust font size for axis titles
    plot.title = element_text(size = 15),  # Adjust font size for title
    panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),   # Remove minor grid lines
    axis.text.x = element_text(angle = 0, hjust = 1),  # Rotate x-axis labels vertically
    panel.background = element_blank(), 
    plot.background = element_blank()) +  
  scale_x_continuous(breaks = seq(-1, 1, by = 0.5), labels = seq(-1, 1, by = 0.5), limits = c(-1, 1), expand = c(0, 0)) +  # Set x-axis limits, breaks, and remove padding
  scale_y_continuous(breaks = seq(0, 15, by = 5), labels = seq(0, 15, by = 5), limits = c(0, 15), expand = c(0, 0))  # Set y-axis breaks and labels 


# Combine the plots with annotation_custom
validation_usaplot_with_hist <- trend_validation +
  annotation_custom(
    grob = ggplotGrob(hist_TP),
    xmin = -2800000, xmax = -1000000,  # Adjust these values for positioning
    ymin = -2500000, ymax = -1000000     # Adjust these values for positioning
  ) +
  theme(panel.background = element_rect(fill = "transparent"))  # Set background to transparent

# Display the final plot
print(validation_usaplot_with_hist)

ggsave("C:\\Research\\TP Analysis\\Figures\\Figure 1\\Correlation.png", plot = validation_usaplot_with_hist, width = 10, height = 8, units = "in", dpi = 1000)


```

